# Projeto Final Aplicado a Ciência de Dados
## Deteção de Outliers em Contratos Públicos e Previsão do Montante de Adjudição

## Grupo 08
## Membros:
###          - Afonso Alexandre nº 123425;
###          - André  Freitas nº 123409;
###          - Gonçalo Vilhena nº 123384;
###          - Rodolfo Nardy nº 123419

In [39]:
import pandas as pd
import numpy as np
import re
import unicodedata

In [40]:
file_path = "contratos_total.csv"
df = pd.read_csv(file_path, low_memory=False)

In [41]:
df.info()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1843246 entries, 0 to 1843245
Data columns (total 35 columns):
 #   Column                    Dtype
---  ------                    -----
 0   idcontrato                int64
 1   nAnuncio                  object
 2   TipoAnuncio               object
 3   idINCM                    float64
 4   tipoContrato              object
 5   idprocedimento            int64
 6   tipoprocedimento          object
 7   objectoContrato           object
 8   descContrato              object
 9   adjudicante               object
 10  adjudicatarios            object
 11  dataPublicacao            object
 12  dataCelebracaoContrato    object
 13  precoContratual           float64
 14  CPV                       object
 15  prazoExecucao             int64
 16  LocalExecucao             object
 17  fundamentacao             object
 18  ProcedimentoCentralizado  object
 19  numAcordoQuadro           float64
 20  DescrAcordoQuadro         object
 21  precoBaseProcedimento     float64
 22  dataDecisaoAdjudicacao    object
 23  dataFechoContrato         object
 24  PrecoTotalEfetivo         float64
 25  regime                    object
 26  justifNReducEscrContrato  object
 27  tipoFimContrato           object
 28  CritMateriais             object
 29  concorrentes              object
 30  linkPecasProc             object
 31  Observacoes               object
 32  ContratEcologico          object
 33  fundamentAjusteDireto     object
 34  Ano                       int64
dtypes: float64(5), int64(4), object(26)
memory usage: 492.2+ MB

Index(['idcontrato', 'nAnuncio', 'TipoAnuncio', 'idINCM', 'tipoContrato',
       'idprocedimento', 'tipoprocedimento', 'objectoContrato', 'descContrato',
       'adjudicante', 'adjudicatarios', 'dataPublicacao',
       'dataCelebracaoContrato', 'precoContratual', 'CPV', 'prazoExecucao',
       'LocalExecucao', 'fundamentacao', 'ProcedimentoCentralizado',
       'numAcordoQuadro', 'DescrAcordoQuadro', 'precoBaseProcedimento',
       'dataDecisaoAdjudicacao', 'dataFechoContrato', 'PrecoTotalEfetivo',
       'regime', 'justifNReducEscrContrato', 'tipoFimContrato',
       'CritMateriais', 'concorrentes', 'linkPecasProc', 'Observacoes',
       'ContratEcologico', 'fundamentAjusteDireto', 'Ano'],
      dtype='object')

In [42]:
(df['LocalExecucao'].str.lower() == "portugal").sum()

np.int64(129122)

In [43]:
percent_nulos = (df.isnull().sum() / len(df)) * 100

# Ordem decrescente
percent_nulos_ordenado = percent_nulos.sort_values(ascending=False)
print(percent_nulos_ordenado)

Observacoes                 94.975549
nAnuncio                    87.816819
TipoAnuncio                 87.816005
idINCM                      87.816005
numAcordoQuadro             87.740649
DescrAcordoQuadro           87.740649
justifNReducEscrContrato    82.739797
linkPecasProc               70.387675
tipoFimContrato             68.284049
dataFechoContrato           67.400390
fundamentAjusteDireto       66.790380
concorrentes                60.417655
dataDecisaoAdjudicacao       2.390782
fundamentacao                2.238497
dataCelebracaoContrato       2.237520
LocalExecucao                2.157770
adjudicatarios               0.111380
descContrato                 0.008084
regime                       0.002821
objectoContrato              0.002496
precoBaseProcedimento        0.001628
CPV                          0.001519
tipoContrato                 0.001465
adjudicante                  0.001085
tipoprocedimento             0.000271
idcontrato                   0.000000
idprocedimento               0.000000
ProcedimentoCentralizado     0.000000
prazoExecucao                0.000000
dataPublicacao               0.000000
precoContratual              0.000000
PrecoTotalEfetivo            0.000000
CritMateriais                0.000000
ContratEcologico             0.000000
Ano                          0.000000
dtype: float64

Apagar os registos em que as datas não fazem sentido

In [44]:
# Guardar ids com data de fecho anterior à celebração
ids_datas_invalidas = df.loc[df["dataFechoContrato"] < df["dataCelebracaoContrato"], "idcontrato"].tolist()
print(f"Contratos com datas inválidas: {len(ids_datas_invalidas)}")
# Remover do df
df = df[~df["idcontrato"].isin(ids_datas_invalidas)]
df = df[df["precoContratual"]>0]
print(f"Contratos restantes: {len(df)}")

Contratos com datas inválidas: 541
Contratos restantes: 1836902

In [45]:
colunas_remover = [
    "nAnuncio",
    "TipoAnuncio",
    "idINCM",
    "numAcordoQuadro",
    "dataFechoContrato",
    "tipoFimContrato",
    "precoBaseProcedimento",
    "PrecoTotalEfetivo",
]

In [46]:
df = df.drop(columns=colunas_remover, errors='ignore')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1836902 entries, 0 to 1843245
Data columns (total 27 columns):
 #   Column                    Dtype
---  ------                    -----
 0   idcontrato                int64
 1   tipoContrato              object
 2   idprocedimento            int64
 3   tipoprocedimento          object
 4   objectoContrato           object
 5   descContrato              object
 6   adjudicante               object
 7   adjudicatarios            object
 8   dataPublicacao            object
 9   dataCelebracaoContrato    object
 10  precoContratual           float64
 11  CPV                       object
 12  prazoExecucao             int64
 13  LocalExecucao             object
 14  fundamentacao             object
 15  ProcedimentoCentralizado  object
 16  DescrAcordoQuadro         object
 17  dataDecisaoAdjudicacao    object
 18  regime                    object
 19  justifNReducEscrContrato  object
 20  CritMateriais             object
 21  concorrentes              object
 22  linkPecasProc             object
 23  Observacoes               object
 24  ContratEcologico          object
 25  fundamentAjusteDireto     object
 26  Ano                       int64
dtypes: float64(1), int64(4), object(22)
memory usage: 392.4+ MB

In [47]:
for col in df.select_dtypes("object"):
    if df[col].astype(str).str.contains("�").any():
        print("Problema encoding em:", col)
        
print(df.loc[df["adjudicatarios"].astype(str).str.contains("�", na=False), ["adjudicatarios"]].head(20))
print(df.loc[df["concorrentes"].astype(str).str.contains("�", na=False), ["concorrentes"]].head(20))

Problema encoding em: adjudicatarios
Problema encoding em: concorrentes
                                    adjudicatarios
1743020  - - Maria Beatriz Nunes Sampaio�b6&#x1F;R
                                    concorrentes
1743020  --Maria Beatriz Nunes Sampaio�b6&#x1F;R

In [48]:
for col in df.select_dtypes("object"):
    
    # remover caractere corrompido
    df[col] = df[col].str.replace("�", "", regex=False)
    
    # remover entidades HTML tipo &#x1F;
    df[col] = df[col].str.replace(r"&#x[0-9A-Fa-f]+;", "", regex=True)
    
    # remover caracteres invisíveis / não imprimíveis
    df[col] = df[col].str.replace(r"[^\x20-\x7EÀ-ÿ]", "", regex=True)

In [49]:
for col in df.select_dtypes(include="object"):
    if df[col].dropna().astype(str).str.startswith(" ").any() or df[col].dropna().astype(str).str.endswith(" ").any():
        print("Espaços extra em:", col)

Espaços extra em: objectoContrato
Espaços extra em: descContrato
Espaços extra em: adjudicante
Espaços extra em: adjudicatarios
Espaços extra em: CPV
Espaços extra em: fundamentacao
Espaços extra em: DescrAcordoQuadro
Espaços extra em: regime
Espaços extra em: justifNReducEscrContrato
Espaços extra em: concorrentes
Espaços extra em: linkPecasProc
Espaços extra em: Observacoes

ver categorias das variaveis

In [50]:
for col in df.select_dtypes(include="object"):
    print("\nColuna:", col)
    print(df[col].value_counts(dropna=False))

Coluna: tipoContrato
tipoContrato
Aquisição de bens móveis                                                            940582
Aquisição de serviços                                                               713157
Empreitadas de obras públicas                                                       143244
Locação de bens móveis                                                               19351
Aquisição de bens móveisAquisição de serviços                                        13129
                                                                                     ...
Aquisição de serviçosEmpreitadas de obras públicasSociedade                              1
Aquisição de bens móveisConcessão de obras públicasSociedade                             1
Aquisição de bens móveisAquisição de serviçosEmpreitadas de obras públicasOutros         1
Aquisição de bens móveisLocação de bens móveisOutros                                     1
Aquisição de serviçosConcessão de obras públicasConcessão de serviços públicos           1
Name: count, Length: 61, dtype: int64

Coluna: tipoprocedimento
tipoprocedimento
Ajuste Direto Regime Geral                                                      1013174
Consulta Prévia                                                                  302489
Concurso público                                                                 219951
Ao abrigo de acordo-quadro (art. 259.)                                           190125
Ao abrigo de acordo-quadro (art. 258.)                                            41047
Ajuste direto simplificado                                                        38623
Contratação excluída II                                                           20562
Concurso limitado por prévia qualificação                                          3487
Setores especiais  isenção parte II                                                2791
Ajuste direto simplificado ao abrigo da Lei n. 30/2021, de 21.05                   2487
Consulta Prévia Simplificada                                                       1851
Concurso público simplificado                                                       116
Procedimento de negociação                                                           84
Consulta prévia ao abrigo do artigo 7 da Lei n. 30/2021, de 21.05                    47
Ajuste Direto Regime Geral ao abrigo do artigo 7 da Lei n. 30/2021, de 21.05         35
Serviços sociais e outros serviços específicos                                       13
Concurso de conceção simplificado                                                     7
Concurso limitado por prévia qualificação simplificado                                6
NaN                                                                                   3
Parceria para a inovação                                                              2
Concurso de ideias simplificado                                                       2
Name: count, dtype: int64

Coluna: objectoContrato
objectoContrato
MEDICAMENTOS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               10889
Medicamentos                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                3220
Aquisição de serviço de viagens e alojamento  Plataforma SIAV                                                                                                                                                                                                                                                                                                                                                                                                                                                                               2209
REAGENTES                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1681
VÁRIOS MEDICAMENTOS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1060
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ...
Encenação, texto, cenografia e figurinos para um bailado                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
Prestação de serviços referente à reparação da máquina  KOMATSU D65-EX, no que respeita ao fornecimento e substituição do material danificado descrito no caderno de encargos.                                                                                                                                                                                                                                                                                                                                                                 1
Prestação de serviços de espectáculos musicais nas Festas de N. Sra Candeias                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
FORNECIMENTO CONTÍNUO DE MATERIAL DE GRÁFICA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
Aquisição de serviços especializados para a conceção e criação de um documentário sobre o património natural do Parque Nacional da Peneda-Gerês (PNPG), que vise promover e valorizar a riqueza ecológica, paisagística e cultural desta área protegida, destacando a sua importância para a conservação da biodiversidade e o desenvolvimento sustentável, segundo as especificações técnicas e termos de referência dos aspetos essenciais da execução do contrato incluídos no Anexo A - cláusulas Técnicas, do caderno de encargos.        1
Name: count, Length: 1362978, dtype: int64

Coluna: descContrato
descContrato
MEDICAMENTOS                                                                                                                                                                                                                    10062
Medicamentos                                                                                                                                                                                                                     2684
Consulta Prévia ao abrigo do acordo-quadro da ESPAP                                                                                                                                                                              2456
Aquisição de serviço de viagens e alojamento  Plataforma SIAV                                                                                                                                                                    2211
REAGENTES                                                                                                                                                                                                                        1497
                                                                                                                                                                                                                                ...
Aquisição de Serviços de Transporte no âmbito de visitas de estudo, saídas de campo e atividades de desporto escolar, para o ano económico de 2026 para grupos superiores a 9 participantes da Escola Secundária Campos Melo        1
Aquisição de Serviços Solução Monitorização PRTG                                                                                                                                                                                    1
PRC/2025/39                                                                                                                                                                                                                         1
Equipamentos de impressão                                                                                                                                                                                                           1
Controlo de Salmonela - ISO6579                                                                                                                                                                                                     1
Name: count, Length: 1390767, dtype: int64

Coluna: adjudicante
adjudicante
506362299 - Instituto Português de Oncologia do Porto Francisco Gentil, E. P. E.    62931
508142156 - Centro Hospitalar Vila Nova de Gaia - Espinho, E. P. E.                 26622
600012662 - Ministério da Defesa Nacional - Marinha                                 25325
508094461 - Unidade Local de Saúde do Norte Alentejano, E. P. E.                    21224
508481287 - Centro Hospitalar Universitário de Lisboa Norte, E. P. E.               20670
                                                                                    ...
501895469 - Associação Social, Cultural e Recreativa de Freixiosa                       1
504341111 - Magensinus - Empresa Promotora de Serviços de Ensino, SA                    1
600061329 - Inspeção-Geral                                                              1
501333967 - Centro Social e Paroquial de Vilar de Perdizes                              1
506656128 - MUNICIPIO DE PAREDES                                                        1
Name: count, Length: 17198, dtype: int64

Coluna: adjudicatarios
adjudicatarios
504223933 - MEDTRONIC PORTUGAL, LDA                                             3739
504223933 - MEDTRONIC PORTUGAL, LDA.                                            3199
500162166 - LAB. PFIZER, LDA.                                                   2888
506019608 - SMILE - VIAGENS E TURISMO, UNIPESSOAL, LDA                          2709
501169580 - LABESFAL-LAB. ALMIRO, SA.                                           2273
                                                                                ...
507553187 - C. Duarte Unipessoal, Lda.                                             1
- - Lígia Maria Rocha Passos                                                       1
980412773 - Medela SL Sucursal Portugal                                            1
- - TVAmadora                                                                      1
505180022 - Folgoconstrói - Sociedade de Construção Civil e Transportes, Lda       1
Name: count, Length: 373871, dtype: int64

Coluna: dataPublicacao
dataPublicacao
2023-05-30    1730
2025-12-30    1608
2025-12-29    1564
2023-12-27    1468
2024-01-03    1460
              ...
2013-06-07       1
2020-08-16       1
2009-01-29       1
2009-06-08       1
2009-05-14       1
Name: count, Length: 3956, dtype: int64

Coluna: dataCelebracaoContrato
dataCelebracaoContrato
NaN           41119
2017-01-02     2072
2016-01-04     1659
2020-01-02     1501
2025-12-30     1495
              ...
2017-03-19        1
2015-08-29        1
2015-08-02        1
2015-11-08        1
2018-09-16        1
Name: count, Length: 4056, dtype: int64

Coluna: CPV
CPV
33600000-6 - Produtos farmacêuticos                                                                                                                                                                                                                                                                                                                                                                                            165746
33000000-0 - Equipamento médico, medicamentos e produtos para cuidados pessoais                                                                                                                                                                                                                                                                                                                                                121724
33140000-3 - Material médico de consumo                                                                                                                                                                                                                                                                                                                                                                                         77103
50000000-5 - Serviços de reparação e manutenção                                                                                                                                                                                                                                                                                                                                                                                 39266
33690000-3 - Medicamentos vários                                                                                                                                                                                                                                                                                                                                                                                                37431
                                                                                                                                                                                                                                                                                                                                                                                                                                ...
45313100-5 - Instalação de elevadores45453100-8 - Obras de recuperação45442110-1 - Pintura de edifícios                                                                                                                                                                                                                                                                                                                             1
39300000-5 - Equipamento diverso92312130-1 - Serviços recreativos das bandas de música                                                                                                                                                                                                                                                                                                                                              1
72262000-9 - Serviços de desenvolvimento de software71330000-0 - Serviços diversos de engenharia73430000-5 - Ensaios e avaliações                                                                                                                                                                                                                                                                                                   1
50300000-8 - Serviços de reparação e manutenção e serviços conexos relacionados com computadores pessoais e com equipamento burótico, audiovisual e para telecomunicações45232300-5 - Construção de linhas telefónicas e de comunicação e obras anexas45233251-3 - Renovação de pavimentos35120000-1 - Sistemas e dispositivos de vigilância e segurança51300000-5 - Serviços de instalação de equipamento para comunicação         1
15321000-4 - Sumos de fruta03140000-4 - Produtos de origem animal e afins15500000-3 - Lacticínios15820000-2 - Tostas, bolachas e biscoitos; produtos de pastelaria e bolos conservados                                                                                                                                                                                                                                              1
Name: count, Length: 19501, dtype: int64

Coluna: LocalExecucao
LocalExecucao
Portugal, Lisboa, Lisboa                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    272946

In [51]:
df["tipoContrato"].dropna().unique()

array(['Aquisição de bens móveis', 'Empreitadas de obras públicas',
       'Aquisição de serviços', 'Locação de bens móveis',
       'Aquisição de bens móveisAquisição de serviços', 'Outros',
       'Aquisição de serviçosLocação de bens móveis',
       'Concessão de serviços públicos',
       'Aquisição de bens móveisLocação de bens móveis',
       'Aquisição de bens móveisSociedade',
       'Aquisição de serviçosSociedade', 'Concessão de obras públicas',
       'Aquisição de serviçosEmpreitadas de obras públicas',
       'Aquisição de bens móveisConcessão de obras públicas',
       'Aquisição de bens móveisEmpreitadas de obras públicas',
       'Aquisição de bens móveisOutros',
       'Aquisição de bens móveisAquisição de serviçosEmpreitadas de obras públicas',
       'Concessão de obras públicasEmpreitadas de obras públicas',
       'Sociedade', 'Aquisição de serviçosOutros',
       'Aquisição de serviçosConcessão de obras públicas',
       'Aquisição de serviçosConcessão de serviços públicos',
       'Locação de bens móveisOutros',
       'Aquisição de bens móveisConcessão de serviços públicos',
       'Empreitadas de obras públicasSociedade',
       'Empreitadas de obras públicasLocação de bens móveis',
       'Concessão de serviços públicosEmpreitadas de obras públicas',
       'Aquisição de bens móveisAquisição de serviçosLocação de bens móveis',
       'Concessão de serviços públicosOutros',
       'Aquisição de bens móveisAquisição de serviçosOutros',
       'Aquisição de serviçosLocação de bens móveisSociedade',
       'Aquisição de serviçosEmpreitadas de obras públicasOutros',
       'Aquisição de bens móveisConcessão de serviços públicosLocação de bens móveis',
       'Concessão de serviços públicosLocação de bens móveis',
       'Aquisição de serviçosConcessão de serviços públicosLocação de bens móveis',
       'Empreitadas de obras públicasOutros',
       'Aquisição de serviçosEmpreitadas de obras públicasLocação de bens móveis',
       'Aquisição de bens móveisAquisição de serviçosConcessão de obras públicas',
       'Aquisição de serviçosLocação de bens móveisOutros',
       'Aquisição de bens móveisAquisição de serviçosConcessão de obras públicasOutros',
       'Aquisição de bens móveisAquisição de serviçosSociedade',
       'Concessão de obras públicasConcessão de serviços públicos',
       'Aquisição de bens móveisLocação de bens móveisSociedade',
       'Locação de bens móveisSociedade',
       'Aquisição de bens móveisEmpreitadas de obras públicasSociedade',
       'Aquisição de bens móveisAquisição de serviçosConcessão de serviços públicos',
       'Aquisição de bens móveisAquisição de serviçosEmpreitadas de obras públicasLocação de bens móveis',
       'Aquisição de serviçosOutrosSociedade',
       'Aquisição de serviçosConcessão de serviços públicosSociedade',
       'Aquisição de bens móveisAquisição de serviçosConcessão de obras públicasConcessão de serviços públicos',
       'Concessão de obras públicasLocação de bens móveis',
       'Aquisição de serviçosConcessão de obras públicasLocação de bens móveis',
       'Aquisição de bens móveisAquisição de serviçosConcessão de obras públicasEmpreitadas de obras públicasOutros',
       'Aquisição de serviçosEmpreitadas de obras públicasSociedade',
       'Aquisição de bens móveisAquisição de serviçosEmpreitadas de obras públicasOutros',
       'Aquisição de bens móveisConcessão de obras públicasSociedade',
       'Aquisição de bens móveisOutrosSociedade',
       'Aquisição de bens móveisLocação de bens móveisOutros',
       'Aquisição de serviçosConcessão de obras públicasConcessão de serviços públicos',
       'Aquisição de bens móveisEmpreitadas de obras públicasLocação de bens móveis'],
      dtype=object)

In [52]:
df["objectoContrato"].dropna().unique()

array(['Prestação de serviços para Elaboração do Projecto dos Edifícios Destinados ao Centro de Incubação de Empresas',
       'Derivados do Plasma, AQ 2012/09',
       'Seringas e Contentores, AQ 2012/22 (Renov 2020014)', ...,
       'Aquisição de serviços especializados para a conceção e fornecimento de materiais personalizados (com logotipos de financiamento e nome/acrónimo do projeto) para construção do Kit pedagógico a ser distribuído pelos alunos e professores participantes nas atividades previstas na operação Conhecer para Preservar e Valorizar (acrónimo: BIONATURE_PNPG) - NORTE2030-FEDER-02711200.',
       'PROPOFOL (2%) 20 MG/ML EMUL INJ FR 50 ML IV',
       'Aquisição de serviços especializados para a conceção e criação de um documentário sobre o património natural do Parque Nacional da Peneda-Gerês (PNPG), que vise promover e valorizar a riqueza ecológica, paisagística e cultural desta área protegida, destacando a sua importância para a conservação da biodiversidade e o desenvolvimento sustentável, segundo as especificações técnicas e termos de referência dos aspetos essenciais da execução do contrato incluídos no Anexo A - cláusulas Técnicas, do caderno de encargos.'],
      shape=(1362977,), dtype=object)

In [53]:
set(df["objectoContrato"].dropna())

{'Serviço de acesso a plataforma eletrónica de gestão de catálogos e de fluxos documentais',
 'TACROLÍMUS 0.5 MG CÁPS LP',
 'EAD20250157 - Material Exclusivo robótica - Excelência robótica',
 'AQ- SERV PA- 25MI508',
 '2022/91 - DGEP - Construção da rampa na Rua Margarida Palla, em Algés',
 'aquisição de serviços de vigilância e segurança para o evento comemorativo dos 75 anos da WSI - WorldSkills ',
 'Aquisição de computadores e multifuncionais no âmbito do protocolo entre a RAM e a PSP (Processo 52/AD/2016)',
 'Fornecimento e suporte de plataformas de voz, monitorização, segurança e ligações cloud, dividido em 4 lotes:Lote 1: Fornecimento de Session border controllers e integração MS Teams com telefonia IP e equipamentos de vídeo e bolsa de horas de serviços de apoio;Lote 2: Expansão de licenciamento da plataforma PRTG Network Monitor, suporte e migração de outras plataformas de monitorização e bolsa de horas de serviços de apoio;Lote 3: Renovação de suporte para equipamentos de segurança de centro de dados, com bolsa de horas de serviços e bolsa de horas de serviços de apoio;Lote 4: Contratação de serviços de ligação Oracle Fastconnect.',
 'Gestão comercial integral de fardamento na PSP',
 'Aquisição de equipamento de laboratório',
 'Serviços de assessoria para planeamento, organização, implementação e acompanhamento do evento Cidade+ 2019.',
 '262_2020 Consumo Clinico XXXI - Torneiras 3 vias',
 'OBRAS DE BENEFICIAÇÃO DOS RECREIOS COBERTOS DA ESCOLA BÁSICA DE DUME E CENTRO ESCOLAR DA NAIA',
 'Fornecimento contínuo de Tubagem e acessórios para a rede de águas do concelho de Nelas - Ano de 2025',
 'Serviços Medicos_Triagem Geral_997039825',
 'Aquisição de materiais técnicos e consumíveis para os Recreios da Amadora',
 'PRC_0314/2023_EXP - 2. optativo do Lote 2  Arouca e Cinfães do Acordo-quadro para empreitadas de reparação e manutenção de redes de abastecimento de água e de saneamento em baixa -PRC_0378/2022_EXP',
 'Trabalhos de adaptação no auditório, estacionamento e iluminação exterior.',
 'A empreitada de Rotunda da Entrada Norte de Vila Real de Santo António, consiste na necessidade de requalificar a EN122, nomeadamente a execução de uma intersecção giratória com duas vias de circulação, passeio e ciclovia. Considerando a existência de um programa de financiamento comunitário aplicável à empreitada em causa denominado PO ALGARVE 21, no sentido de estimular o crescimento sustentado da economia portuguesa, e concretamente da região.',
 'Aquisição de bicicletas e material acessório - Plano Municipal de Promoção da utilização da Bicicleta (PMPUB) Fase 2 2019/2020 ',
 '27 nebulizadores a frio, para desinfeção',
 'Locação de equipamentos de som, luz e de audiovisual para 2 (dois) espetáculos.',
 'PROCESSO 20205710399 - AQUISIÇÃO DE DIVERSOS MATERIAIS (LUVAS, DESINFETANTE E TERMÓMETROS) PARA APLICAÇÃO DE PLANO DE CONTIGÊNCIA RELATIVO AO COVID-19 ',
 'Aquisicão da VAC CONTRA POLIOMIELITE (VIP) (IMOVAX POLIO) SER IM SC - 2025 - ULSLO',
 '98/DHRU/DPRH/2016 - Reparação de fogo devoluto sito na rua António Macedo n. 9, 2 fte',
 'Imagem promocional da Cidade do Funchal-Complexos das Piscinas Olímpicas do Funchal',
 'Demolição de Prédio em Ruinas, Rua Dr. Delfim Pinheiro, n 13',
 '201G001251 - ACETILCISTEINA 600 MG COMP EFERVESCENTE',
 'Aquisição de serviços de realização de diversos trabalhos gráficos durante os anos 2024 e 2025',
 '91/CLPQ/AT/2024 - Aquisição de serviços de manutenção e suporte de equipamentos HPE do Datacenter da AT',
 'Empreitada CONSERVAÇÃO CORRETIVA DO PAVIMENTO 2025 NORTE - 7 LOTES',
 'Serviços para a elaboração do Projeto Técnico de Reabilitação de 179 fogos de Habitação Social ',
 'Prestação de Serviços para o Desenvolvimento das Atividades de Enriquecimento Curricular (AEC) e de duas Atividades no âmbito das Atividades de Animação e Apoio à Família (AAAF) nas Escolas Básicas do 1 ciclo e  Jardins  de  Infância  da  Rede  Pública  do  Concelho  de  Oliveira  do  Bairro  no  ano  letivo 2024/2025',
 'Projeto de execução para "Requalificação e refuncionalização da casa amarela para Centro de Investigação e Promoção da Cidade Romana da Bobadela"',
 'Empreitada de pavimentação da Av. Cidade de Coimbra',
 '05-CPR-ISCAP-2024  Fornecimento urgente de equipamento informático para reforçar o Instituto Superior de Contabilidade e Administração do Porto (ISCAP)',
 '3023003256/Fornecimento de Sobressalentes para Emergency Request',
 'Contratação dos Serviços de Cópia e Impressão em Outsourcing por 4 Meses',
 'Serviço de aluguer de equipamentos de apoio à visita guiada em grupo - 2018',
 'Aquisição urgente de máscaras FFP2',
 'Aquisição de sacos de elevação de 5 m3 para contentores semienterrados de RSU',
 '2021002242 - Fe Carboximaltose ferrica 50 mg/ml Sol inj Fr 10 ml IV',
 'aquisição de serviços de produção de plataforma de leilão eletrónico',
 'Serviços para reparação equipamento de frio',
 'serviços de mudança da infraestrutura tecnológica da SVEP afeta à Vigilância Eletrónica',
 'Fornecimento de inertes para pavimentações em alcatrão - Ano 2017',
 'Aquisição de Ventiladores para a Desodorização da Fábrica de Água da Guia - Fase Líquida - TA_22_292_CI_B_011_DGA',
 'Monitorização dos Recursos Hídricos Superficiais na Rede Secundária de Rega em Fase de Exploração - 2019/2020',
 'Aquisição de serviços ao abrigo do Lote 1 do AQ-SDASI, designadamente Contratação de serviços de análise, de especificação funcional e técnica, de desenho, de desenvolvimento, e de execução de testes para implementação de novos sistemas',
 '24/AQ/DMMC/DEM/DPCE/21  COORDENAÇÃO POR MODELAÇÃO BIM PARA O EDIFÍCIO DO QUARTEL DA 6. COMPANHIA DO RSB  MARVILA  PRC. 40/AQS/AD/DGES/ND/2021',
 'Fornecimento e Montagem de Escada em Plástico Reciclado de Acesso ao Ancoradouro de Uso Publico de Castanheira ',
 '16EP00002081 - EMPREITADA DE REMODELAÇÃO DOS SISTEMAS DE PRODUÇÃO DE ENERGIA TÉRMICA, GESTÃO TÉCNICA CENTRALIZADA NO PALÁCIO DA JUSTIÇA DE SINTRA',
 'Aquisição de Dispositivos médicos, para o Hospital Prof. Dr. Fernando Fonseca, EPE, para o ano 2020, no âmbito do COVID-19.',
 'Aquisição de Fibroscópio portátil para UCIP',
 '3022014875 - MATERIAL DE APOIO A UNIDADE',
 'AQUISIÇÃO DE SERVIÇOS URGENTE PARA LIMPEZA, DESINFEÇÃO E HIGIENIZAÇÃO COVID-19 DO PAVILHÃO MUNICIPAL DE DESPORTOS E DO PAVILHÃO MULTIUSOS',
 '2021004961 - Material aplicado ao doente,EXT 1091020 /BLOC 112 De 2021',
 'ADC 084/16 - Fornecimento com montagem de um elevador de duas colunas para oficina auto',
 'Aquisição de livros de fichas e manuais para as AEC para os alunos do 1, 2 e 3 ciclos do Ensino Básico',
 'Aquisição de serviços de consultoria para definição do modelo organizacional do SMO e planeamento do PRR da Justiça.',
 'Inspeções periódicas das instalações de gás em escolas',
 'PRC_0269/2023_LAB - Aquisição de reagentes e consumíveis para o Laboratório da Águas do Norte, S.A.. Lote 1. 1. renovação.',
 'Consumíveis e reagentes de laboratório',
 'MEDICAMENTOS EXCLUSIVOS ORIONFIN',
 'Reabilitação dos Alçados da Escola, com Revestimento em Madeira - EB da Praia',
 'Fornecimento e Instalação de Pavimento para Parque Exterior do Centro Comunitário António Aleixo ',
 'Requalificação dos Caminhos Valdujo/Moreirinhas/Terrenho',
 'Aquisição de fornecimento de refeições para as unidades orgânicas dos Serviços Centrais e Delegação Regional de Lisboa e Vale do Tejo do Instituto do Emprego e Formação Profissional, IP, para o período de 5 meses ',
 '18143000-Equipamento (vestuário) de protecção PAQ 1357/2020',
 'Beneficiação do Cemitério de Alvaiade',
 'Equipar sala de aula de multimédia',
 'S10017/2017 Fornecimento de Serviços de Exames de Gastro - CPRE aos Doentes do CHBM, EPE',
 'Renovação do Lote II do Procedimento n. 82/2019 - Aquisição de serviços de seguros',
 '040005252015 REAGENTES PARA O SERVIÇO DE PATOLOGIA CLINICA',
 '68.326.2020 Cat Aplicação Ekanban',
 '20747015 - AD para Aquisição de Monof Polipropileno 4/0 Ag Dupla Cil 16mm 1/2 circulo',
 'Marcos de deposição, sistema de elevação e pavimentos metálicos',
 'Aquisição de serviços para elaboração do projecto de execução de muro de suporte de terras na Azinhaga da Sardinha, União das Freguesias de Sintra',
 'L.NORTE /L.BEIRA ALTA- ADAPTAÇÃO DO FASEAMENTO DA ESTAÇÃO DA PAMPILHOSA',
 'Contrato de aquisição de combustíveis rodoviários ao abrigo do lote 1 do acordo quadro de fornecimento de combustíveis rodoviários para o Gabinete do Ministro da Economia e do Mar.',
 'Substituição da Ponte Pedonal da Forca',
 'AQUISIÇÃO DE SERVIÇOS PARA A ELABORAÇÃO DE PROJECTO E CADERNO DE ENCARGOS DE EMPREITADA DE OBRA PARA REABILITAÇÃO DA CASA DA NORA',
 'PAQ.346/2018-Aluguer de Monopostes Publicitários pelo período de 6 meses',
 'Ajuste Direto para aquisição 8 aspiradores urbanos elétricos ao abrigo do Acordo Quadro/14/2018',
 'Fornecimento de catálogos para as exposições e dois livros para o Museu do Neo-Realismo - VFX',
 'Assegurar a limpeza das instalações da Biblioteca do Município de Valpaços e facultar apoio nas atividades levadas a efeito na Biblioteca Municipal',
 'CCP 0016-2025 Empreitada de Obras Públicas  Instalação e Reparação da Rede Elétrica em Abrigo dos Pequeninos N. Sr. da Conceição - Covilhã',
 '2020ADAPTAR/P.L 02',
 'Empreitada de Pavimentação do Heliporto de Moura',
 'Requalificação/Calcetamento do Caminho do Codessal e da Calçada da Bouça',
 'Aquisição de sistema de monitorização HR e T para a Igreja de Nossa Senhora da Graça, Santarém',
 'Aquisição de combustíveis rodoviários e para aquecimento',
 '500025071 - Aquisição de Serviços para Formação Avançada em Gestão de Marketing e Venda Consultiva',
 '4021005176 - LMPQF ADS - Fraldas e campo operatório',
 'AD/130/2024 _ Reparação Gerador',
 'PC 0281/AT/21 - PROTESE CAPILAR',
 ' ELABORAÇÃO DE PROJETO DE EXECUÇÃO PARA A REABILITAÇÃO DO EDIFÍCIO DO PALÁCIO DUCAL',
 'Empreitada Extraordinária Imprevisível e Urgente 253/2016 - Bairro Olivais Sul, Rua Cidade de Benguela, Lote 337 - R/C Esq - Reabilitação de fogo municipal - Contrato Programa 398/CM/2015 - Acção XXII Sub-acção 22.213',
 '5001/18/0000252 Serviço de manutenção de SRH Plus E SSD',
 '41/9055/2025 - Ajuste direto para aquisição de A93 - ACIDO AMINOCAPRÓICO [25%; FRS/AMP; IV] e A94 - ACIDO AMINOCAPRÓICO [3G; SAQUETA/ CART].',
 '259/VIAG/2024 - Deslocação a Bruxelas',
 'DAP 2025.0163 - Aquisição de Serviços de Lavagem de Roupa  janeiro de 2026 ',
 'AD 37/2025 - Aquisição de Projeto de Arquitetura e Especialidades de Adaptação de infraestruturas do i3S para instalação do Centro de Medicina de Precisão do Norte (CEMPRE-N)',
 'Serviços de assistência técnica do elevador (Masel), para o período compreendido entre 01 de setembro de 2019 a 31 de agosto de 2020.',
 'CP 02/15 - Aquisição de serviços para atividades e eventos por professores e técnicos para as Piscinas Municipais de Gondomar',
 'Aquisição de consumíveis de impressão, durante o ano de 2018',
 'Aquisição de diverso material para diagnóstico para execução dos planos oficiais 2024',
 'O objeto do contrato consiste numa prestação de serviços na modalidade de avença na área do aprovisionamento',
 'Aquisição de serviços de técnico de manutenção da condição fisica',
 'Prestação de Serviços - Cozinheiro',
 'Aquisição de Equipamentos Locals - Edição Páscoa',
 'Fornecimento de energia elétrica de média tensão',
 'PRC_0159/2021_EXP - Aquisição de Sistemas de remoção de gradados-Grelhas Verticais para a Águas do Norte, S.A. - Lote 2',
 'FORNECIMENTO E INSTALAÇÃO DE 2 ECRÃ E BRAÇO DE SUPORTE PARA OS SERVIÇOS FARMACÊUTICOS',
 '128003424  Aquisição de Impressoras para o SSTI da ULSLO',
 'Prestação de Serviços de Exploração e Manutenção de Todos os Sistemas de Abastecimento de Água para Consumo Humano do Concelho de Vimioso de forma a garantir água em quantidade e qualidade em todos os locais de abastecimento (2019-2023)',
 'CLAFA - DAT - ALUGUER DE 10 VIATURAS ATÉ DOZE MESES',
 'Fornecimento e distribuição de leite e produtos lácteos aos alunos que frequentam os estabelecimentos de ensino publico do pré-escolar e 1 ciclo do ensino básico do município de santo tirso',
 'Aquisição de Serviços de Assessoria Jurídica, Representação Judiciária e Mandato Forense às empresas do Grupo SIMAB',
 'Aquisição de Extintores para as Unidades, Estabelecimentos e Órgãos da FAP',
 'Aquisição de módulo sanitário pré-fabricado ',
 'Aquisição de Serviços de Animação, Decoração e Iluminação para a Noite Preta 2025',
 'AQUISIÇÃO DE COMBUSTÍVEL ÀS FORÇAS ARMADAS ALEMÃS',
 'CPG/17/2020 - Reparação/Manutenção da Estação de Bombagem da Fonte Luminosa, junto à Câmara Municipal',
 'Meios de Diagnóstico, Kits para Pacientes',
 'Aquisição de Bolos de Pastelaria',
 'FORNECIMENTO DE SUPLEMENTOS ALIMENTARES',
 'aquisição de uma unidade de medida CPU (LTC112) para a estação meteorológica da BA5',
 'Prestação de Serviços de Segurança e Vigilância no Silo Auto de Armação de Pera',
 '3017010267/DA/Kit de Peças NR1',
 'Prestação de Serviços de Assessoria de Imprensa e Comunicação',
 '11803269 - Aquisição de Dispositivo médico para o serviço de Urgência e Unidades de Cuidados Intensivos (HSFX) e do serviço de Pediatria (HSFX) do CHLO.E.P.E.',
 'Produção de espetáculos artísticos das Festas do Concelho - 2025',
 'Aquisição de 1 Bisturi Elétrico Bipolar para Bloco Operatório do Serviço de Urgência do CHSJ, EPE',
 'CP TB27/2025 - TRANSPORTE DE BENS PESSOAIS',
 'Material Eléctrico para UGB',
 'Serviços de limpeza dos balneários e áreas comuns dos campos multifuncionais e do relvado n. 2 do complexo desportivo - ano de 2019',
 'FORNECIMENTO DE 480 COMPUTADORES PORTÁTEIS',
 'Ajuste Direto n 1/2025 Consultoria de Custos com Energia Elétrica',
 '22C00024 - Aquisição de auricular para telefone fixo necessário para atendimento de chamadas para marcações de testes no âmbito do programa de testagem à Covid-19 ',
 'PM 001/Angra do Heroísmo  Castelo S. João Batista, Campo Relvão e CT de Angra do Heroísmo (RG1/ZMA) - Remodelação da Caserna dos Recrutas.',
 '80487316 - AD para Reparação de Automóveis',
 'Fiscalização da Iluminação Pública do Largo de S. João Novo',
 'Fornecimento de um Conjunto de Cintas Bipartidas para o Travelift Existente no Centro Náutico de São Lázaro no Porto do Funchal',
 'Aquisição de reagentes de microbiologia - AjD 80061416',
 'Aquisição de Serviços de Transporte de Alunos com Medidas de Suporte à Aprendizagem e Inclusão (MSAI) não cadeirantes para o Ano Letivo 2023/2024',
 'Fempark Assistência C/Menfor',
 'DIVERSO MATERIAL CLÍNICO  ANCA CIMENTADA',
 'Fornecimento e instalação de equipamento infantil, em espaço a criar na Freguesia',
 'Rent-a-car de uma viatura ligeira de mercadorias, para a equipa da manutenção da Bragahabit',
 'Fornecimento de Óticas para Histeroscopia',
 'LIGADURA SOFLEX AUTOADESIVA ',
 'Aquisição de sistema de segurança',
 'CANULA TRAQUEOSTOMIA FENESTRADA SEM CUFF N9- PC.00520.2024',
 'Hardware - Infraestrutura de Servidor Blade',
 'FORNECIMENTO DE JANTAR DE NATAL PARA OS COLABORADORES DO MUNICÍPIO DE VIEIRA DO MINHO  ANO 2024',
 'TRABALHOS COMPLEMENTARES À REQUALIFICAÇÃO DAS INSTALAÇÕES SANITARIAS DA UNIDADE DE ENSINO ESPECIAL-EB/JI DE CAXINAS',
 'Ajuste Direto n. 58/2018 - Aquisição de utensílios isotérmicos para transporte de refeições escolares.',
 'Aquisição de produtos alimentares diversos-bufete.',
 'AQUISIÇÃO DE SERVIÇOS DE TÉCNICO DE INFORMÁTICA',
 'Elaboração de projeto eletrotécnico e telecomunicações/Localidade de Montevil',
 'Ajuste direto Simplificado de aquisição de DECK Compósito',
 'PM 001/Amadora  Quartel N. 1 da Amadora ou Antigo Aeródromo  Adaptação de edifício para Capela da Academia Militar.',
 ' CONTRATAÇÃO DE AÇÕES DE PROMOÇÃO DO TERRITÓRIO - CONSERVAS PINHAIS FACTORY TOUR',
 'Aquisição de Testes Psicológicos no âmbito do Projeto "Núcleo de Intervenção com os Alunos e Famílias"',
 'Aquisição do Serviço de Transporte de colaboradores do INIAV IP entre o Metro do Mindelo e o Polo de Vairão e vice-versa, para o período de janeiro de 2024 a dezembro de 2025',
 'Serviços de comunicações de voz fixas, móveis, TV e internet',
 'CPREV003DGE2025 - Aquisição de Sanitários Ecológicos',
 'Substituição e atualização do sistema de iluminação do edifício J1 para sistemas LED',
 'EMPREITADA DE OBRAS PARA DIVERSOS TRABALHOS NO  RECOBRO - BLOCO OPERATÓRIO DO HSFX.',
 'Realização de empreitada para remodelação dos pisos cave, 2, 3, 4 e 6 andares nas instalações da Fundação para a Ciência e a Tecnologia (FCT, I.P), sitas na Av. D. Carlos I, n. 126, em Lisboa',
 'O presente procedimento tem como objeto a aquisição de serviços de promoção da qualidade das aprendizagens iniciais em Matemática no âmbito do Plano Intermunicipal de Promoção do Sucesso Escolar do Algarve , abreviadamente designado por PIPSE - ALGARVE',
 'Aquisição de serviços musicais  concerto Banda Sinfónica Portuguesa',
 'ADENOSINA ,6MG/2ML SOL INJ FR 2ML IVADRENALINA,1MG/1ML SOL INJ FR 1ML  I.C  IM IV SCAMIODARONA 150 MG / 3 ML SOL INJ FR 3 ML IVAMIODARONA 200 MG CAP/COMPAMLODIPINA    5MG      COMPATROPINA 0,5MG/1ML SOL INJ AMP 1ML IM IV SCBISOPROLOL 5 mg CompCARVEDILOL,   25MG,COMPCARVEDILOL,6.25MG,COMPCLONIDINA 0,15MG COMPESPIRONOLACTONA,100MG,COMPESPIRONOLACTONA,25MG,COMPFUROSEMIDA 40MG COMPFUROSEMIDA,20MG/2ML SOL INJ,FR 2ML IM/IVLISINOPRIL,20MG,COMPMETOPROLOL 100 MG COMPMONONITRATO ISOSSORBIDO 20 MG CAPNebivolol 5 mg CompNIFEDIPINA 30 MG COMP LPNIMODIPINA,30MG,COMPNORADRENALINA,1MG/ ML SOL INJ FR 5 ML IVPROPRANOLOL 10 MG COMPPROPRANOLOL 40 MG COMPRAMIPRIL 1,25 MG COMPRAMIPRIL 5 MG CAPSRosuvastatina 10 mg CompSINVASTATINA,20MG, COMPValsartan 80 mg CompADRENALINA,1MG/1ML SOL INJ FR 1ML  I.C  IM IV SCAMIODARONA 150 MG / 3 ML SOL INJ FR 3 ML IV',
 'Aquisição de serviços para a Coordenação de Segurança e Saúde para a fase de obra da empreitada: "Requalificação da zona envolvente ao cemitério, Rua da Eirinha e Via de acesso à Autoestrada - Serzedelo"',
 'Aquisição de material para eletromecânica para o Armazém do serviço de Instalações e Equipamentos do CHULN',
 '182G010273 - Consumíveis Serv. Cardiologia',
 'Aluguer de equipamento de audiovisual para o Colete Encarnado 2019',
 'Pretende-se a requalificação do edifício do antigo Centro de dia para construção da extensão de saúde da Póvoa de Rio de Moinhos',
 'Aquisição de serviços para a elaboração do projeto de conceção da ligação da EN 329-1 a Germil',
 'Fornecimento de combustíveis rodoviários',
 'Aquisição Urgente de várias Suturas - Unidade Local de Saúde Lisboa Ocidental - Ano de 2025.',
 'Consulta Prévia n32/2022 - Aquisição de serviços de transporte para Visita de Estudo a Coimbra',
 'AQUISIÇÃO DE CAFÉ, CEVADA, DESCAFEINADO, CHÁ E ADOÇANTES',
 'Aquisição de Serviços de Licenciamento e Suporte das Plataformas de Virtualização VMware e Citrix e Sistema de Backups Veeam Backup and Replication',
 '31/3580/2024 - Medicamento Eptinezumab 100 mg/ml Sol inj Fr 1 ml IV',
 'Prestação de serviços de segurança no âmbito do Decreto-Lei n. 65/2021',
 '3009-3020004271_AQUISIÇÃO DE PAPEL DE FOTOCÓPIA A4 80G PARA CONSUMO DA DIREÇÃO',
 'Aquisição de humidificadores com água estéril',
 'PRESTAÇÃO DE SERVIÇOS NA ÁREA DE FOTOGRAFIA E VÍDEO PARA RECOLHA DE IMAGENS EM EVENTOS DA CMS, PELO PERÍODO DE 4 MESES',
 'Fornecimento de refeições a confecionar em refeitórios das escolas básicas de 2, 3 ciclo e secundárias da rede publica do concelho do Seixal. (2022/300.10.005/1203)',
 'APRESENTAÇÃO DO ESPETÁCULO ILS NOUS ONT OBLIÉS',
 'Processo n 20173710597 - Aquisição de serviços de cedência de instalações para formação profissional e serviços conexos, em Vila Nova de Gaia, para o desenvolvimento das seguintes ações de formação: EFA B3 17.0093  Pintura de Construção Civil e EFA B3, 17.0094  Assistente Familiar e de Apoio à Comunidade - Ano  2017 e 2018.',
 'Comemorações do Dia do Concelho - Aquisição de Catering com toda a logística e almoço de Gala',
 'Os serviços objeto do contrato são prestados no Edifício dos Serviços Técnicos de Viana do Castelo, sito na Rua Bernardo Abrunhosa, n. 105, 4900-309 Viana do Castelo.',
 'GLECAPREVIR 100MG E PIBRENTASVIR 40MG COMP (MARIVET)',

Preços corrigidos para 2025

In [54]:
# garantir tipos corretos
df["precoContratual"] = pd.to_numeric(df["precoContratual"], errors="coerce")
df["dataPublicacao"] = pd.to_datetime(df["dataPublicacao"], errors="coerce")

# extrair ano do contrato
df["ano_contrato"] = df["dataPublicacao"].dt.year

# taxas anuais do IPC (Pordata, coluna Total)
taxas_ipc = {
    2015: 0.005,
    2016: 0.006,
    2017: 0.014,
    2018: 0.010,
    2019: 0.003,
    2020: 0.000,
    2021: 0.013,
    2022: 0.078,
    2023: 0.043,
    2024: 0.024,
    2025: 0.023,
}

def atualizar_para_2025(preco, ano):
    if pd.isna(preco) or pd.isna(ano):
        return np.nan
    
    ano = int(ano)
    
    # se o contrato for posterior a 2025, não ajusta
    if ano >= 2025:
        return preco
    
    fator = 1.0
    
    # multiplica do ano seguinte até 2025
    for a in range(ano + 1, 2026):
        fator *= (1 + taxas_ipc.get(a, 0))
    
    return preco * fator

df["precoContratual_2025"] = df.apply(
    lambda row: atualizar_para_2025(row["precoContratual"], row["ano_contrato"]),
    axis=1
)

print(df[["dataPublicacao", "ano_contrato", "precoContratual", "precoContratual_2025"]].head(10))

  dataPublicacao  ano_contrato  precoContratual  precoContratual_2025
0     2009-06-05          2009         12000.00          14869.407217
1     2015-01-02          2015            40.50             49.934576
2     2015-01-02          2015         21646.00          26688.489936
3     2015-01-02          2015         11647.50          14360.814309
4     2015-01-02          2015         16139.20          19898.867078
5     2015-01-02          2015         39400.00          48578.328720
6     2008-10-30          2008         36529.96          45264.904239
7     2009-05-07          2009          9760.00          12093.784537
8     2015-01-02          2015        600607.50         740520.521994
9     2015-01-02          2015        281238.60         346753.836535

Corrigir o prazoExecucao e precoContratual

In [55]:
df['setor_cpv'] = df['CPV'].astype(str).str.extract(r'^(\d{2})')
df['descricao_cpv'] = df['CPV'].astype(str).str.extract(r'^\d+(?:-\d+)?\s*-\s*(.*)$')
df['racio_preco_prazo'] = np.where(
    df['prazoExecucao'] > 0,
    df['precoContratual_2025'] / df['prazoExecucao'],
    np.nan
)

In [56]:
def calcular_limites(grupo):
    return pd.Series({
        "mediana": grupo["prazoExecucao"].median(),
        "limite_superior": grupo["prazoExecucao"].quantile(0.99),
        "descricao_cpv": grupo["descricao_cpv"].dropna().mode().iloc[0] if not grupo["descricao_cpv"].dropna().empty else None

    })

limites_cpv = df.groupby(df['setor_cpv']).apply(calcular_limites)

C:\Users\goncalo\AppData\Local\Temp\ipykernel_4120\86878064.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  limites_cpv = df.groupby(df['setor_cpv']).apply(calcular_limites)

In [57]:
df_prazo_igual_1 = df[df['prazoExecucao'] == 1]
df = df[~df["idcontrato"].isin(df_prazo_igual_1["idcontrato"])]
len(df)

1761141

In [58]:
def calcular_limites_precos(grupo):
    return pd.Series({
        "mediana_racio": grupo["racio_preco_prazo"].median(),
        "limite_superior_racio": grupo["racio_preco_prazo"].quantile(0.99),
        "descricao_cpv": grupo["descricao_cpv"].dropna().mode().iloc[0] if not grupo["descricao_cpv"].dropna().empty else None

    })
limites_cpv_precos = df.groupby(df['setor_cpv']).apply(calcular_limites_precos)

C:\Users\goncalo\AppData\Local\Temp\ipykernel_4120\3895538263.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  limites_cpv_precos = df.groupby(df['setor_cpv']).apply(calcular_limites_precos)

In [59]:
def contratos_acima_limite(df, limites_cpv):
    resultado = []

    for setor, grupo in df.groupby('setor_cpv'):
        if setor not in limites_cpv.index:
            continue

        limite = limites_cpv.loc[setor, 'limite_superior']

        print(f"Setor: {setor} | Limite: {limite}")

        ids_acima = grupo.loc[grupo['prazoExecucao'] > limite, 'idcontrato'].tolist()
        resultado.extend(ids_acima)

    total = len(resultado)
    perc = total / len(df) * 100
    print(f"Total de contratos acima do limite superior Prazos: {total}")
    print(f"Percentagem de contratos acima do limite superior Prazos: {perc:.3f}%")

    return resultado

ids_outliers = contratos_acima_limite(df, limites_cpv)
df = df[~df['idcontrato'].isin(ids_outliers)]

Setor: 03 | Limite: 1095.0
Setor: 09 | Limite: 1096.0
Setor: 14 | Limite: 1096.0
Setor: 15 | Limite: 1095.0
Setor: 16 | Limite: 1096.0
Setor: 18 | Limite: 1095.0
Setor: 19 | Limite: 1096.0
Setor: 22 | Limite: 1096.0
Setor: 24 | Limite: 1096.0
Setor: 30 | Limite: 1096.0
Setor: 31 | Limite: 1096.0
Setor: 32 | Limite: 1096.0
Setor: 33 | Limite: 1095.0
Setor: 34 | Limite: 1800.0
Setor: 35 | Limite: 1095.0
Setor: 37 | Limite: 847.9200000000037
Setor: 38 | Limite: 1095.0
Setor: 39 | Limite: 1095.0
Setor: 41 | Limite: 1556.0199999999918
Setor: 42 | Limite: 1096.0
Setor: 43 | Limite: 1096.0
Setor: 44 | Limite: 1096.0
Setor: 45 | Limite: 730.0
Setor: 48 | Limite: 1096.0
Setor: 50 | Limite: 1096.0
Setor: 51 | Limite: 1096.0
Setor: 55 | Limite: 1826.0
Setor: 60 | Limite: 1440.0
Setor: 63 | Limite: 1095.0
Setor: 64 | Limite: 1461.0
Setor: 65 | Limite: 1461.0
Setor: 66 | Limite: 1826.0
Setor: 70 | Limite: 5953.759999999984
Setor: 71 | Limite: 1096.0
Setor: 72 | Limite: 1096.0
Setor: 73 | Limite: 1096.0
Setor: 75 | Limite: 1460.0
Setor: 76 | Limite: 1096.0
Setor: 77 | Limite: 1096.0
Setor: 79 | Limite: 1096.0
Setor: 80 | Limite: 1096.0
Setor: 85 | Limite: 1096.0
Setor: 90 | Limite: 1096.0
Setor: 92 | Limite: 1095.0
Setor: 98 | Limite: 1096.0
Total de contratos acima do limite superior Prazos: 13510
Percentagem de contratos acima do limite superior Prazos: 0.767%

In [60]:
limites_cpv.sort_values('limite_superior', ascending=False)

,mediana,limite_superior,descricao_cpv
setor_cpv,,,
70,180.0,5953.76,Serviços de arrendamento ou locação de bens im...
55,49.0,1826.00,Serviços de fornecimento de refeições (catering)
66,365.0,1826.00,Serviços de seguros
34,60.0,1800.00,Equipamento e produtos auxiliares de transporte
41,45.0,1556.02,Água captada e tratada
65,365.0,1461.00,Serviços públicos
64,640.0,1461.00,Serviços de telecomunicações
75,349.0,1460.00,Serviços relacionados com a administração pública
60,180.0,1440.00,Serviços de transporte rodoviário de passageir...
16,30.0,1096.00,Maquinaria agrícola
14,279.0,1096.00,"Saibro, areia, brita e agregados"
22,40.0,1096.00,Material impresso e afins
09,365.0,1096.00,Electricidade
76,329.0,1096.00,Serviços relacionados com as indústrias do gás...
77,214.0,1096.00,Serviços de plantação e manutenção de áreas ve...
79,214.0,1096.00,"Serviços a empresas: direito, comercialização,..."
80,240.0,1096.00,Serviços de ensino e formação
30,30.0,1096.00,"Máquinas, equipamento e material de escritório..."
24,210.0,1096.00,Produtos químicos
31,30.0,1096.00,"Maquinaria, aparelhagem, equipamento e consumí..."
32,30.0,1096.00,"Equipamento de rádio, televisão, comunicação, ..."
19,30.0,1096.00,"Materiais têxteis, de couro, de plástico e de ..."
51,43.0,1096.00,Serviços de instalação (excepto software)
71,150.0,1096.00,"Serviços de arquitectura, construção, engenhar..."
50,90.0,1096.00,Serviços de reparação e manutenção
48,365.0,1096.00,Pacotes de software e sistemas de informação
44,30.0,1096.00,Estruturas e materiais de construção; produtos...
42,30.0,1096.00,Máquinas industriais
43,30.0,1096.00,Equipamento para parques e áreas de recreação
98,197.0,1096.00,Serviços diversos
90,330.0,1096.00,Serviços de limpeza
72,365.0,1096.00,"Serviços de TI: consultoria, desenvolvimento d..."
73,210.0,1096.00,Serviços de investigação e desenvolvimento e s...
85,225.0,1096.00,Serviços de saúde e acção social
18,30.0,1095.00,Equipamento (vestuário) de protecção
03,210.0,1095.00,"Produtos da agricultura, da pesca, da silvicul..."
15,335.0,1095.00,"Produtos alimentares, bebidas, tabaco e produt..."
33,117.0,1095.00,Produtos farmacêuticos
38,30.0,1095.00,"Equipamento laboratorial, óptico e de precisão..."
35,30.0,1095.00,Equipamento de segurança e protecção
63,30.0,1095.00,Serviços de agências de viagens e serviços sim...
39,30.0,1095.00,"Mobiliário (incl. de escritório), acessórios, ..."
92,30.0,1095.00,"Serviços recreativos, culturais e desportivos"
37,30.0,847.92,"Instrumentos musicais, artigos de desporto, jo..."
45,60.0,730.00,Construção

In [61]:
def contratos_acima_limite_precos(df, limites_cpv_precos):
    resultado = []

    for setor, grupo in df.groupby(df['setor_cpv']):
        if setor not in limites_cpv_precos.index:
            continue
        limite = limites_cpv_precos.loc[setor, 'limite_superior_racio']
        ids_acima = grupo.loc[grupo['racio_preco_prazo'] > limite, 'idcontrato'].tolist()
        resultado.extend(ids_acima)

    total = len(resultado)
    perc = total / len(df) * 100
    print(f"Total de contratos acima do limite superior racio precos: {total}")
    print(f"Percentagem de contratos acima do limite superior racio precos: {perc:.3f}%")

    return resultado

ids_outliers_precos = contratos_acima_limite_precos(df, limites_cpv_precos)
df = df[~df['idcontrato'].isin(ids_outliers_precos)]

Total de contratos acima do limite superior racio precos: 16988
Percentagem de contratos acima do limite superior racio precos: 0.972%

In [62]:
limites_cpv_precos.sort_values('limite_superior_racio', ascending=False)

,mediana_racio,limite_superior_racio,descricao_cpv
setor_cpv,,,
92,188.247518,23722.471465,"Serviços recreativos, culturais e desportivos"
55,282.151371,19032.000164,"Serviços de hotelaria, restauração e comércio ..."
09,172.406797,18241.679205,Electricidade
34,338.585353,13591.191023,Equipamento e produtos auxiliares de transporte
35,231.816667,13280.449907,Equipamento de segurança e protecção
32,520.565255,12974.325278,"Equipamento de rádio, televisão, comunicação, ..."
16,507.188014,12788.250390,Maquinaria agrícola
79,100.036612,12277.769488,"Serviços a empresas: direito, comercialização,..."
43,545.027342,12178.622317,Equipamento para parques e áreas de recreação
45,910.925166,12003.263266,Construção
48,123.287671,11807.507444,Pacotes de software e sistemas de informação
33,50.638500,11732.554900,Produtos farmacêuticos
65,54.730153,10856.336352,Serviços públicos
51,291.604969,10804.563363,Serviços de instalação (excepto software)
30,132.504669,10410.757207,"Máquinas, equipamento e material de escritório..."
38,285.944465,9041.348885,"Equipamento laboratorial, óptico e de precisão..."
22,128.106752,8898.602726,Material impresso e afins
90,100.988027,8895.990243,Serviços de limpeza
18,215.859921,8687.261142,Equipamento (vestuário) de protecção
14,89.802471,8582.450918,"Saibro, areia, brita e agregados"
76,113.647631,8466.719968,Serviços relacionados com as indústrias do gás...
63,131.764446,8401.657768,Serviços de agências de viagens e serviços sim...
31,206.671873,8234.660830,"Maquinaria, aparelhagem, equipamento e consumí..."
98,58.084239,8040.950422,Serviços diversos
39,221.764097,7817.232694,"Mobiliário (incl. de escritório), acessórios, ..."
60,82.786125,7767.182555,Serviços de transporte rodoviário de passageir...
37,392.403021,7624.537349,"Instrumentos musicais, artigos de desporto, jo..."
70,66.711924,7349.526486,Serviços de arrendamento ou locação de bens im...
42,317.899175,7297.599861,Máquinas industriais
85,57.304579,6179.062740,Serviços de saúde e acção social
44,159.207910,6127.985730,Estruturas e materiais de construção; produtos...
03,75.016308,5471.057150,"Produtos da agricultura, da pesca, da silvicul..."
19,99.861918,5444.129377,"Materiais têxteis, de couro, de plástico e de ..."
50,81.840000,5225.167377,Serviços de reparação e manutenção
24,47.640725,5178.813131,Produtos químicos
72,77.814401,4772.129995,"Serviços de TI: consultoria, desenvolvimento d..."
41,34.520548,4491.920031,Água captada e tratada
66,50.449315,4446.746708,Serviços de seguros
75,46.398941,4160.158562,Serviços relacionados com a administração pública
77,162.141928,4084.666600,Serviços de plantação e manutenção de áreas ve...
71,153.450000,3891.560395,"Serviços de arquitectura, construção, engenhar..."
15,35.741384,3829.120728,"Produtos alimentares, bebidas, tabaco e produt..."
73,90.822104,3571.117893,Serviços de investigação e desenvolvimento e s...
64,27.172040,3387.391241,Serviços de telecomunicações
80,30.137812,1983.606810,Serviços de ensino e formação

In [63]:
df = pd.concat([df, df_prazo_igual_1]).reset_index(drop=True)
len(df)

1806404

In [64]:
ids_repetidos = df[df["idcontrato"].duplicated(keep=False)]
df = df[~df["idcontrato"].isin(ids_repetidos["idcontrato"])]

In [65]:
ids_repetidos.groupby('idcontrato')['dataCelebracaoContrato'].nunique().gt(1).sum()

ids_repetidos = (
    ids_repetidos
    .sort_values('dataCelebracaoContrato')
    .drop_duplicates('idcontrato', keep='last')
)
print(len(ids_repetidos))

2911

In [66]:
antes = len(df)
df = pd.concat([df, ids_repetidos]).reset_index(drop=True)
print(f"Contratos adicionados: {len(df) - antes}")
print(f"Contratos totais: {len(df)}")

Contratos adicionados: 2911
Contratos totais: 1803493

Limpeza dos campos de adjudicatários, adjudicantes e concorrentes

In [67]:
def separar_entidades_por_nif(texto):
    if pd.isna(texto):
        return pd.NA

    texto = str(texto).strip()
    if texto == '':
        return pd.NA

    # converter sequências escapadas em quebras reais
    texto = texto.replace('\\n', '\n').replace('\\r', '\n').replace('\\t', ' ')

    # normalizar espaços sem destruir \n
    texto = re.sub(r'[ \t]+', ' ', texto)

    # quebrar antes de cada novo NIF, exceto no início
    texto = re.sub(r'(?<!^)(\d{9})', r'\n\1', texto)

    partes = [p.strip() for p in texto.split('\n') if p.strip()]

    return '\n'.join(partes) if partes else pd.NA

df['concorrentes'] = df['concorrentes'].apply(separar_entidades_por_nif)
df['adjudicatarios'] = df['adjudicatarios'].apply(separar_entidades_por_nif)
df['adjudicante'] = df['adjudicante'].apply(separar_entidades_por_nif)

In [68]:
def limpar_texto_base(texto):
    if pd.isna(texto):
        return pd.NA

    texto = str(texto).strip()
    if texto == '':
        return pd.NA

    # maiúsculas
    texto = texto.upper()

    # remover acentos
    texto = unicodedata.normalize('NFD', texto)
    texto = ''.join(c for c in texto if unicodedata.category(c) != 'Mn')

    # corrigir html
    texto = texto.replace('&AMP;', '&')

    # normalizações específicas
    texto = texto.replace('B BRAUN', 'BBRAUN')
    texto = re.sub(r'\bLAB\b', 'LABORATORIOS', texto)

    # remover pontuação
    texto = re.sub(r'[.,;:\-_/\\()]+', ' ', texto)

    texto = re.sub(r'\b(LDA|LDA\.|SA|S A|S\.A\.|UNIPESSOAL|S A U|SAU|SL|S L|SUCURSAL)\b', '', texto)

    # normalizar espaços
    texto = re.sub(r'[ \t]+', ' ', texto).strip()

    return texto if texto != '' else pd.NA

Funções para limpar nomes com NIF

In [69]:

def limpar_nome_com_nif(valor):
    if pd.isna(valor):
        return pd.NA

    valor = str(valor).strip()
    if valor == '':
        return pd.NA

    valor = valor.replace('\\n', '\n').replace('\\r', '\n').replace('\\t', ' ')
    valor = re.sub(r'\s+', ' ', valor).strip()

    match = re.match(r'^(\d{9})\s*[,;:\-]?\s*(.*)$', valor)
    if match:
        nif = match.group(1)
        nome = match.group(2).strip()
        nome = limpar_texto_base(nome)
        if pd.isna(nome) or nome == '':
            return nif
        return f'{nif}, {nome}'

    nome = limpar_texto_base(valor)
    return nome


def limpar_lista_nomes_com_nif(valor):
    """
    Para colunas tipo concorrentes, preservando \n.
    Divide por linhas e também por NIFs repetidos na mesma linha.
    """
    if pd.isna(valor):
        return pd.NA

    valor = str(valor).strip()
    if valor == '':
        return pd.NA

    itens_limpos = []

    linhas = valor.split('\n')

    for linha in linhas:
        linha = linha.strip()
        if not linha:
            continue

        # separa antes de cada NIF de 9 dígitos
        partes = re.split(r'(?=\b\d{9}\s)', linha)

        for parte in partes:
            parte = parte.strip()
            if not parte:
                continue

            limpo = limpar_nome_com_nif(parte)
            if pd.notna(limpo) and limpo != '':
                itens_limpos.append(limpo)

    # remover duplicados preservando ordem
    itens_limpos = list(dict.fromkeys(itens_limpos))

    return '\n'.join(itens_limpos) if itens_limpos else pd.NA


def criar_mapa_primeiro_nome_por_nif(serie):
    tmp = serie.str.extract(r'^(\d{9})[\s,]+(.*)$')
    tmp.columns = ['nif', 'nome']

    mapa = (
        tmp.dropna(subset=['nif', 'nome'])
        .drop_duplicates(subset='nif', keep='first')
        .set_index('nif')['nome']
    )

    return mapa


def aplicar_mapa_nif_nome(valor, mapa_nomes):
    if pd.isna(valor):
        return pd.NA

    valor = str(valor).strip()
    match = re.match(r'^(\d{9})[\s,]+(.*)$', valor)
    if not match:
        return valor

    nif = match.group(1)

    if nif in mapa_nomes.index and pd.notna(mapa_nomes[nif]):
        return f'{nif}, {mapa_nomes[nif]}'

    return valor

def aplicar_mapa_nif_nome_em_lista(valor, mapa_nomes):
    if pd.isna(valor):
        return pd.NA

    valor = str(valor).replace('\\n', '\n').replace('\\r', '\n').replace('\\t', ' ')
    linhas = valor.split('\n')
    novas_linhas = []

    for linha in linhas:
        linha = linha.strip()
        if not linha:
            continue

        nova = aplicar_mapa_nif_nome(linha, mapa_nomes)
        if pd.notna(nova) and nova != '':
            novas_linhas.append(nova)

    novas_linhas = list(dict.fromkeys(novas_linhas))

    return '\n'.join(novas_linhas) if novas_linhas else pd.NA

limpar as colunas

In [70]:
df['adjudicatarios'] = df['adjudicatarios'].apply(limpar_nome_com_nif)


df['concorrentes'] = df['concorrentes'].apply(limpar_lista_nomes_com_nif)

df['adjudicante'] = df['adjudicante'].apply(limpar_nome_com_nif)

Normalização dos adjudicatários por NIF

In [71]:
mapa_nomes_adjudicatarios = criar_mapa_primeiro_nome_por_nif(df['adjudicatarios'])

df['adjudicatarios'] = df['adjudicatarios'].apply(
    lambda x: aplicar_mapa_nif_nome(x, mapa_nomes_adjudicatarios)
)

Normalização dos concorrentes

In [72]:

df['concorrentes'] = df['concorrentes'].apply(
    lambda x: aplicar_mapa_nif_nome_em_lista(x, mapa_nomes_adjudicatarios)
)

Normalização dos adjudicantes

In [73]:

mapa_nomes_adjudicante = criar_mapa_primeiro_nome_por_nif(df['adjudicante'])

df['adjudicante'] = df['adjudicante'].apply(
    lambda x: aplicar_mapa_nif_nome(x, mapa_nomes_adjudicante)
)

In [74]:
def remover_adjudicatario_dos_concorrentes(row):

    if pd.isna(row['adjudicatarios']) or pd.isna(row['concorrentes']):
        return row['concorrentes']

    vencedor = row['adjudicatarios'].strip()

    concorrentes = [
        c.strip()
        for c in str(row['concorrentes']).split('\n')
        if c.strip() != ''
    ]

    # remover adjudicatário dos concorrentes
    concorrentes_limpos = [
        c for c in concorrentes
        if c != vencedor
    ]

    # Se não sobrar nada → NaN
    if len(concorrentes_limpos) == 0:
        return pd.NA

    # Voltar a juntar com newline
    return '\n'.join(concorrentes_limpos)


# Aplicar ao dataframe
df['concorrentes'] = df.apply(
    remover_adjudicatario_dos_concorrentes,
    axis=1
)

In [75]:

df["dataCelebracaoContrato"] = pd.to_datetime(df["dataCelebracaoContrato"], errors="coerce")

datas_al = pd.to_datetime([
    "2017-10-01",
    "2021-09-26",
    "2025-10-12"
])

datas_ar = pd.to_datetime([
    "2015-10-04",
    "2019-10-06",
    "2022-01-30",
    "2024-03-10",
    "2025-05-18"
])

datas_todas = datas_al.tolist() + datas_ar.tolist()



df["janela_eleicoes"] = "não"
df["AR"] = "não"
df["AL"] = "não"


for data_eleicao in datas_todas:
    mask_antes = (
        (df["dataCelebracaoContrato"] >= data_eleicao - pd.DateOffset(months=3)) &
        (df["dataCelebracaoContrato"] < data_eleicao)
    )

    mask_depois = (
        (df["dataCelebracaoContrato"] >= data_eleicao) &
        (df["dataCelebracaoContrato"] <= data_eleicao + pd.DateOffset(months=3))
    )

    df.loc[mask_antes, "janela_eleicoes"] = "3 meses antes"
    df.loc[mask_depois, "janela_eleicoes"] = "3 meses depois"


for data_eleicao in datas_ar:
    mask_ar = (
        (df["dataCelebracaoContrato"] >= data_eleicao - pd.DateOffset(months=3)) &
        (df["dataCelebracaoContrato"] <= data_eleicao + pd.DateOffset(months=3))
    )

    df.loc[mask_ar, "AR"] = "sim"



for data_eleicao in datas_al:
    mask_al = (
        (df["dataCelebracaoContrato"] >= data_eleicao - pd.DateOffset(months=3)) &
        (df["dataCelebracaoContrato"] <= data_eleicao + pd.DateOffset(months=3))
    )

    df.loc[mask_al, "AL"] = "sim"



print(df["janela_eleicoes"].value_counts(dropna=False))
print(df["AR"].value_counts(dropna=False))
print(df["AL"].value_counts(dropna=False))

janela_eleicoes
não               1156969
3 meses antes      330008
3 meses depois     316516
Name: count, dtype: int64
AR
não    1352971
sim     450522
Name: count, dtype: int64
AL
não    1560633
sim     242860
Name: count, dtype: int64

In [76]:
df.to_csv("contratos_limpo.csv", index=False)